#ifndef ERROR_HANDLING_H
#define ERROR_HANDLING_H

typedef enum
{
    SYS_STATUS_OK = 0,
    SYS_ERROR_TIM0_INIT_INPUT_INVALID_WGM,
    SYS_ERROR_TIM0_INIT_INPUT_INVALID_PRESCALER,
    SYS_ERROR_TIM0_INIT_INPUT_INVALID_OUTPUT_CMP_A,
    SYS_ERROR_TIM0_INIT_INPUT_INVALID_OUTPUT_CMP_B,
    SYS_ERROR_TIM0_INIT_INPUT_INVALID_INTERRUPT_FLAG,
    SYS_ERROR_TIM0_INPUT_INVALID_COUNT_OUT_OF_RANGE,

    SYS_ERROR_TIM1_INIT_INPUT_INVALID_WGM,
    SYS_ERROR_TIM1_INIT_INPUT_INVALID_PRESCALER,
    SYS_ERROR_TIM1_INIT_INPUT_INVALID_OUTPUT_CMP_A,
    SYS_ERROR_TIM1_INIT_INPUT_INVALID_OUTPUT_CMP_B,
    SYS_ERROR_TIM1_INIT_INPUT_INVALID_INTERRUPT_FLAG,
    SYS_ERROR_TIM1_INPUT_INVALID_COUNT_OUT_OF_RANGE,
    
    SYS_ERROR_TIM2_INIT_INPUT_INVALID_WGM,
    SYS_ERROR_TIM2_INIT_INPUT_INVALID_PRESCALER,
    SYS_ERROR_TIM2_INIT_INPUT_INVALID_OUTPUT_CMP_A,
    SYS_ERROR_TIM2_INIT_INPUT_INVALID_OUTPUT_CMP_B,
    SYS_ERROR_TIM2_INIT_INPUT_INVALID_INTERRUPT_FLAG,
    SYS_ERROR_TIM2_INPUT_INVALID_COUNT_OUT_OF_RANGE,

    SYS_MARKER_END_OF_LIST
}sys_err_e_t;

#endif